#@TYPE: Machine
#@NAME: imdt-v2n-sbc machine
#@DESCRIPTION: IMDT RZ/V2N Single board computer

require conf/machine/include/rzv2n-family.inc
require conf/machine/include/imdt-v2-sbc.inc

# Add SoC part number to overrides so COMPATIBLE_MACHINE patterns match
MACHINEOVERRIDES .= "r9a09g056:rzv2n-evk"

IMAGE_BOOT_FILES += " \
    Flash_Writer_SCIF_RZV2N_DEV_LPDDR4X.mot \
"

TFA_PLATFORM = "v2n"

UBOOT_CONFIG = "imdt-v2n-sbc"

# Set u-boot defconfig to use
UBOOT_CONFIG[imdt-v2n-sbc] = "${MACHINE}_defconfig"
