#@TYPE: Machine
#@NAME: imdt-v2h-sbc machine
#@DESCRIPTION: IMDT V2H Single Board Computer

require conf/machine/include/rzv2h-family.inc
require conf/machine/include/imdt-v2-sbc.inc

# Add SoC part number to overrides so COMPATIBLE_MACHINE patterns match
MACHINEOVERRIDES =. "r9a09g057:rzv2h-evk:"

IMAGE_BOOT_FILES += " \
    Flash_Writer_SCIF_RZV2H_DEV_INTERNAL_MEMORY.mot \
"
TFA_PLATFORM = "v2h"
UBOOT_CONFIG = "imdt-v2h-sbc"

# Set u-boot defconfig to use
UBOOT_CONFIG[imdt-v2h-sbc] = "${MACHINE}_defconfig"