#@TYPE: Machine
#@NAME: imdt-v2h-sbc machine
#@DESCRIPTION: IMDT V2H Single Board Computer

SOC_FAMILY = "r9a09g057"
require conf/machine/include/imdt-v2-sbc.inc
UBOOT_CONFIG ??= "imdt-v2h-sbc"
UBOOT_CONFIG[imdt-v2h-sbc] = "${MACHINE}_defconfig"
