#@TYPE: Machine
#@NAME: imdt-v2n-sbc machine
#@DESCRIPTION: IMDT RZ/V2N Single board computer

SOC_FAMILY = "r9a09g056"
require conf/machine/include/imdt-v2-sbc.inc
UBOOT_CONFIG ??= "imdt-v2n-sbc"
UBOOT_CONFIG[imdt-v2n-sbc] = "${MACHINE}_defconfig"
