# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILES_DYNAMIC += "\
     meta-rz-codecs:${LAYERDIR}/dynamic-layers/meta-rz-codecs/recipes-*/*/*.bbappend \
     meta-rz-graphics:${LAYERDIR}/dynamic-layers/meta-rz-graphics/recipes-*/*/*.bbappend \
     meta-rz-codecs:${LAYERDIR}/dynamic-layers/recipes-*/*/*.bbappend \
     rz-drpai:${LAYERDIR}/dynamic-layers/meta-rz-drpai/recipes-*/*/*.bb \
     rz-drpai:${LAYERDIR}/dynamic-layers/meta-rz-drpai/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "imdt-renesas"
BBFILE_PATTERN_imdt-renesas = "^${LAYERDIR}/"
BBFILE_PRIORITY_imdt-renesas = "20"
LAYERDEPENDS_imdt-renesas = "meta-rz-bsp meta-rz-distro swupdate"

LAYERSERIES_COMPAT_imdt-renesas = "scarthgap"