# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILES_DYNAMIC += "\
    rz-drpai:${LAYERDIR}/dynamic-layers/meta-rz-drpai/recipes-*/*/*.bb \
    rz-drpai:${LAYERDIR}/dynamic-layers/meta-rz-drpai/recipes-*/*/*.bbappend \
    rz-codecs:${LAYERDIR}/dynamic-layers/meta-rz-codecs/recipes-*/*/*.bbappend \
    rz-opencva:${LAYERDIR}/dynamic-layers/meta-rz-opencva/recipes-*/*/*.bbappend \
    rz-graphics:${LAYERDIR}/dynamic-layers/meta-rz-graphics/recipes-*/*/*.bbappend \
    rz-codecs:${LAYERDIR}/dynamic-layers/recipes-*/*/*.bbappend \
    rz-opencva:${LAYERDIR}/dynamic-layers/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "imdt-renesas"
BBFILE_PATTERN_imdt-renesas = "^${LAYERDIR}/"
BBFILE_PRIORITY_imdt-renesas = "20"

LAYERDEPENDS_imdt-renesas = "rz-common rzv2h"
LAYERSERIES_COMPAT_imdt-renesas = "dunfell"

# Add a file containing the git commit hashes of the layers that contributed to this image build (/etc/build)
INHERIT += " image-buildinfo"

# Apply mirror to avoid missing Debian security tarballs
MIRRORS += " \
  https://security.debian.org/debian-security/pool/updates https://debian.sipwise.com/debian-security/pool \n \
"
