require conf/distro/rz-vlp.conf

DISTRO = "imdt"
DISTRO_NAME = "IMDT (Renesas RZ)"
BB_ENV_PASSTHROUGH_ADDITIONS:append = " IMDT_DISTRO_VERSION"
IMDT_DISTRO_VERSION ?= "0.0.0"
DISTRO_VERSION = "${IMDT_DISTRO_VERSION}"
DISTROOVERRIDES = "rz-bsp:rz-vlp:imdt"

SYSTEMD_AUTO_ENABLE:pn-auditd = "disable"

# Package configuration
PACKAGE_CLASSES ?= "package_rpm"

# License flags
LICENSE_FLAGS_ACCEPTED = " \
    commercial_gstreamer1.0-plugins-ugly \
    commercial_mpeg2dec \
    commercial_gst-plugins-bad \
    commercial_faad2 \
    commercial_faac \
    commercial_gstreamer1.0-libav \
    commercial_ffmpeg commercial_x264 \
"

# Build info in image
INHERIT += "image-buildinfo"

# Debian snapshot mirrors for reproducible builds
PREMIRRORS += " \
    http://security.debian.org/debian-security/ https://snapshot.debian.org/archive/debian-security/20240701T000000Z/ \n \
    https://security.debian.org/debian-security/ https://snapshot.debian.org/archive/debian-security/20240701T000000Z/ \n \
    http://deb.debian.org/debian/ https://snapshot.debian.org/archive/debian/20240701T000000Z/ \n \
    https://deb.debian.org/debian/ https://snapshot.debian.org/archive/debian/20240701T000000Z/ \n \
    http://ftp.debian.org/debian/ https://snapshot.debian.org/archive/debian/20240701T000000Z/ \n \
    https://ftp.debian.org/debian/ https://snapshot.debian.org/archive/debian/20240701T000000Z/ \n \
    https://ftp.gnu.org/ https://ftpmirror.gnu.org/ \n \
    http://ftp.gnu.org/ https://ftpmirror.gnu.org/ \n \
"

PACKAGECONFIG:append:pn-gstreamer1.0-plugins-ugly = " x264"